[package]
name = "image-viewer"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.45"
eframe = { version = "0.36", features = ["glow"] }
egui = "0.36.1"
egui_extras = { version = "0.36", features = ["all_loaders"] }
image = "0.24"
image-webp = "0.2.4"
libloading = "0.9.0"
num-format = "0.4.4"
rfd = "0.17.2"
turbojpeg = { version = "1.5.1", features = ["image"] }
webp-animation = "0.10.0"
windows-sys = { version = "0.61.2", features = ["Win32_Graphics_Gdi"] }
